default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: hotwire_forum_development

test:
  <<: *default
  database: hotwire_forum_test

production:
  <<: *default
  database: hotwire_forum_production
  username: hotwire_forum
  password: <%= ENV['HOTWIRE_FORUM_DATABASE_PASSWORD'] %>
